export let options = {
    accessToken: null,
    origin: "https://api.mapbox.com",
    // mapboxgl: mapbox,
    zoom: 16,
    flyTo: true,
    placeholder: "Search",
    proximity: "ip",
    trackProximity: true,
    collapsed: false,
    clearAndBlurOnEsc: false,
    clearOnBlur: false,
    bbox: undefined,
    countries: undefined,
    types: undefined,
    minLength: 2,
    limit: 5,
    language: undefined,
    filter: undefined,
    localGeocoder: undefined,
    externalGeocoder: undefined,
    reverseMode: "distance",
    reverseGeocode: false,
    flipCoordinates: false,
    enableEventLogging: false,
    marker: true,
    render: undefined,
    getItemValue: (item) => item.place_name,
    mode: "mapbox.places",
    localGeocoderOnly: false,
    autocomplete: false,
    fuzzyMatch: true,
    routing: false,
    worldview: "us",
    enableGeolocation: false,
    addressAccuracy: "street",
};
