export let options = {
    accessToken: null,
    antialias: false,
    attributionControl: true,
    bearing: 0,
    bearingSnap: 7,
    bounds: null,
    boxZoom: true,
    center: [0,0],
    clickTolerance: 3,
    collectResourceTiming: false,
    container: undefined,
    cooperativeGestures: false, // ?
    crossSourceCollisions: true,
    customAttribution: null,
    doubleClick: true,
    dragPan: true,
    dragRotate: true,
    fadeDuration: 300,
    failIfMajorPerformanceCaveat: false,
    fitBoundsOptions: undefined, // ?
    hash: false,
    interactive: true,
    keyboard: true,
    language: null,
    locale: null,
    localFontFamily: false,
    localIdeographFontFamily: 'sans-serif',
    logoPosition: 'bottom-left',
    maxBounds: null,
    maxPitch: 85,
    maxTileCacheSize: null,
    maxZoom: 22,
    minPitch: 0,
    minTileCacheSize: null,
    minZoom: 0,
    optimizeForTerrain: true,
    performanceMetricsCollection: true,
    pitch: 0,
    pitchWithRotate: true,
    preserveDrawingBuffer: false,
    projection: 'mercator',
    refreshExpiredTiles: true,
    renderWorldCopies: false, // I changed this from mapbox's default
    scrollZoom: true,
    style: 'mapbox://styles/mapbox/dark-v10',
    testMode: false,
    touchPitch: true,
    touchZoomRotate: true,
    trackResize: true,
    transformRequest: null,
    useWebGL2: false,
    worldview: null,
    zoom: 0
}